# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gograpple < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/gograpple"
  version "0.0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/foomo/gograpple/releases/download/v0.0.11/gograpple_0.0.11_darwin_amd64.tar.gz"
    sha256 "7f0db223e6976b8fc5e0b34cbe4434d856deb628d8e97180bfea4c3858b836fc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/foomo/gograpple/releases/download/v0.0.11/gograpple_0.0.11_linux_amd64.tar.gz"
    sha256 "dbeb289eb0878cc1d802cf1a122a8a60894b480d00b47f95eaa1acb546aca0a2"
  end

  def install
    bin.install "gograpple"
  end

  def caveats; <<~EOS
    gograpple -h
  EOS
  end
end
